vim.keymap.set('v', 'y', '"+y', { noremap = true })
vim.keymap.set('v', 'p', '"+p', { noremap = true })
vim.keymap.set('v', 'x', '"+x', { noremap = true })
vim.keymap.set('v', 'y', '"+y')
vim.keymap.set('v', 'p', '"+p')
